[package]
name = "luby_transform"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.21.7"
wasm-bindgen = "0.2.90"
js-sys = "0.3.68"
web-sys = { version = "0.3.68", features = ["console"] }

[profile.release]
opt-level = "s"
